puts "The students of Villains Academy"
puts "_____________"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Rached"
puts "Michael Corleone"
puts "Alex Delarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"

print "Overall we have "
print "11"
puts " great students"
